### PR TITLE
autograd-gamma 0.5.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/CamDavidsonPilon/autograd-gamma/releases
License: https://github.com/CamDavidsonPilon/autograd-gamma/blob/master/LICENSE
Requirements: https://github.com/CamDavidsonPilon/autograd-gamma/blob/master/setup.py

Actions:
1. Apply an initial **percy** [patch](https://github.com/anaconda-distribution/percy/blob/main/percy/examples/patch/test_patch.json) and run locally a [script](https://github.com/anaconda-distribution/percy/blob/main/percy/examples/patch/updater_standalone.py) to: 
  - Remove `noarch python`
  - Skip `py<37`
  - Add flags `--no-deps --no-build-isolation` to `script`
  - Add missing `setuptools` and `wheel` to `host`
  - Fix `python` in `host` and `run`

Notes:
- `lifelines` requires it https://github.com/conda-forge/lifelines-feedstock/blob/532bab4fccd8407f9e4e4010ab6733951ef254e8/recipe/meta.yaml#L36

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Before merging I'll remove https://github.com/AnacondaRecipes/autograd-gamma-feedstock/blob/479ce10226eecd797e14c3ce16af1ffa36c68a6e/abs.yaml

**Comment by M-Waszkiewicz-Anaconda** [comment]
forgot to add all other changes to meta.yaml ?

**Comment by skupr-anaconda** [comment]
> forgot to add all other changes to meta.yaml ?

Ah, no. I've mistakenly pushed changes to the `main` branch before creating a new branch [autograd-gamma-_0.6.0](https://github.com/AnacondaRecipes/autograd-gamma-feedstock/tree/autograd-gamma-_0.6.0) and opening the PR :(

**Review by akabanovs — APPROVED** [review]
So I believe the changes have been already merged before creating a new branch. But the recipe as it is now looks good.

**Pull request merged**
